const collegeList = [
    "Delhi University",
    "IIT Delhi",
    "NSUT",
    "IIIT Delhi",
    "DTU",
    "Jamia Millia Islamia",
    "Ambedkar University",
    "IGNOU",
    "SRCC",
    "Lady Shri Ram College",
    "Hindu College",
    "Hansraj College",
    "Miranda House",
    "St. Stephen's College",
    // GGSIPU University Schools
    "University School of Architecture and Planning (USAP)",
    "University School of Basic & Applied Sciences (USBAS)",
    "University School of Biotechnology (USBT)",
    "University School of Chemical Technology (USCT)",
    "University School of Environment Management (USEM)",
    "University School of Humanities & Social Sciences (USHSS)",
    "University School of Information and Communication Technology (USICT)",
    "University School of Law and Legal Studies (USLLS)",
    "University School of Management Studies (USMS)",
    "University School of Mass Communication (USMC)",
    "University School of Medicine and Para-Medical Health Sciences (USMPHS)",
    "University School of Automation and Robotics (USAR)",
    "University School of Design & Innovation (USDI)",
    // GGSIPU Affiliated Government Institutions
    "Ch. Brahm Prakash Ayurved Charak Sansthan, Najafgarh",
    "Bhai Parmanand Institute of Business Studies, Shakarpur",
    "C-DAC under Govt. of India, Sector 62, Noida",
    "Delhi Institute of Heritage Research & Management",
    "Dr. Baba Saheb Ambedkar Medical College and Hospital, Rohini",
    "National Power Training Institute, Badarpur, New Delhi",
    "North Delhi Municipal Corporation Medical College and Hindu Rao Hospital, Malka Ganj",
    "Vardhman Mahavir Medical College and Safdarjung Hospital, Ansari Nagar West",
    "Atal Bihari Vajpayee Institute of Medical Sciences and Dr. Ram Manohar Lohia Hospital, Talkatora Road",
    // GGSIPU Affiliated Private Colleges and Institutes
    "Rukmini Devi Institute of Advanced Studies (RDIAS), Rohini",
    "Army College of Medical Sciences, Delhi Cantonment",
    "B. M. Institute of Engineering & Technology, Sonipat, Haryana",
    "Bhagwan Mahaveer College of Engineering and Management, Sonipat District, Haryana",
    "Banarsidas Chandiwala Institute of Management and Technology, Dwarka",
    "Banarsidas Chandiwala Institutes, Chandiwala Estate, Okhla NSIC",
    "Institute of Hotel Management & Catering",
    "Institute of Information Technology",
    "Institute of Physiotherapy",
    "Bhagwan Parshuram Institute of Technology, Rohini",
    "Bharati Vidyapeeth, Paschim Vihar",
    "Chandraprabhi Jain College of Higher Studies, Narela",
    "COMM-IT, Career Academy, Sheikh Sarai",
    "Delhi Technical Campus, Greater Noida",
    "Delhi Institute of Technology & Management, Shastri Nagar",
    "Delhi Metropolitan Education, Sector 62, Noida",
    "Delhi School of Professional Studies and Research (DSPSR), Rohini",
    "Delhi Institute of Advanced Studies (DIAS), Rohini",
    "Fairfield Institute of Management and Technology, Kapashera",
    "Gitarattan International Business School, Rohini",
    "Guru Nanak College, Punjabi Bagh",
    "Guru Ram Dass College, Shahdara",
    "Guru Tegh Bahadur Institute of Technology, Hari Nagar",
    "Ideal Institute of Management & Technology, Vivek Vihar",
    "Institute of Information Technology and Management (IITM 1), Janakpuri",
    "Institute of Innovation in Technology and Management (IITM 2), Janakpuri",
    "Maharaja Surajmal College, Janakpuri",
    "Maharaja Surajmal Institute",
    "Maharaja Surajmal Institute of Technology",
    "Management Education & Research Institute (MERI), Janakpuri",
    "Maharaja Agrasen College, Rohini",
    "Maharaja Agrasen Institute of Management Studies",
    "Maharaja Agrasen Institute of Technology",
    "New Delhi Institute of Management (NDIM), Tughlakabad Institutional Area, Tigri",
    "Dr. Akhilesh Das Gupta Institute of Professional Studies, Shastri Park",
    "Sirifort Institute of Management Studies (SIMS), Rohini",
    "Sri Guru Tegh Bahadur Institute of Management and Information Technology, Mukherjee Nagar",
    "Tecnia Institute of Advanced Studies, Rohini",
    "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "Jagan Institute of Management Studies (JIMS), Rohini",
    "Jagannath International Management School (JIMS), Vasant Kunj",
    "Jagannath International Management School (JIMS), Kalkaji",
    "Jagan Institute of Management Studies (JIMS), Greater Noida",
    "Kalka Institute of Education and Research, Alakananda",
    "KCC Institute Of Legal and Higher Education, Greater Noida",
    "Kasturi Ram College of Higher Education, Narela",
    "Lingaya's Lalita Devi Institute of Management & Sciences, Mandi Village",
    "Lal Bahadur Institute of Management, Dwarka",
    "Trinity Institute of Professional Studies (TIPS), Dwarka",
    // Add more colleges as needed
  ];
  
  export default collegeList;
  